import React from 'react'

export default function Info() {
    return (
        <>
        <h3>INFO</h3>
        <p>This is the info section</p>

        <p>This is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info sectionThis is the info section</p>

        </>
    )
}